### ISSUE TITLE
Crash on Dedicates Server

### ISSUE THREAD

**Issue by Slither88** [EnderiumSmith/CharcoalPit2#2]
I am using forge 36.1.4 and 2.11.1 of Charcoal pit and I get the below crash on my dedicated server:

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[custom.jar:36.1] {}
-- MOD charcoal_pit --
Details:
	Mod File: CharcoalPit[1.16.5]-2.11.1.jar
	Failure message: Charcoal Pit (charcoal_pit) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
	Mod Version: 2.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[custom.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_271] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_271] {}

**Comment by EnderiumSmith** [comment]
yes that tends to be a recurring issue. But that report doesnt actually say which thing crashes.

**Comment by Slither88** [comment]
Sorry. Forgot to attach the actual crash report.
[crash-2021-04-17_17.48.09-server.txt](https://github.com/EnderiumSmith/CharcoalPit2/files/6330036/crash-2021-04-17_17.48.09-server.txt)

**Comment by EnderiumSmith** [comment]
that is an unrelated crash report

**Comment by Slither88** [comment]
[crash-2021-04-17_10.07.56-fml.txt](https://github.com/EnderiumSmith/CharcoalPit2/files/6333922/crash-2021-04-17_10.07.56-fml.txt)
 Sorry. Idk why I did not check before uploading.

**Comment by EnderiumSmith** [comment]
again that also doesnt contain the full report.

anyway i found it. it turns out to be quite old. i dont know why no one reported it before.
